app/Http/routes.php
<?php

// Authentication routes
Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/landingpage', 'PagesController@landingpage');

    // ------------------------------------------------
    // Auth routes
    // ------------------------------------------------

    Route::get('/auth', 'PagesController@showLogin');
    Route::post('/auth', 'AuthController@login');
    Route::get('/logout', ['as' => 'logout', 'uses' => 'AuthController@logout']);
    Route::get('/admin/{category}', ['as' => 'dashboard', 'uses' => 'AdminController@showDashboard']);
    Route::get('/admin', ['as' => 'dashboard', 'uses' => 'AdminController@showDashboard']);

    // ------------------------------------------------
    // Publications
    // ------------------------------------------------

    Route::get('/publication/{year}', 'PublicationsController@index');
    Route::get('/publicationsfiles', 'PublicationsController@fileManager');
    Route::resource('/publication', 'PublicationsController', ['except' => ['destroy']]);
    Route::get('/publication/{id}/destroy', 'PublicationsController@destroy');
    Route::get('/publication/create/{type}', 'PublicationsController@create');
    Route::post('/publication/filter', 'PublicationsController@filter');
    Route::post('/publication/storeFiles', 'PublicationsController@storeFile');
    Route::post('/publications/storeHtml', ['as' => 'publication.storeHtml', 'uses' => 'PublicationsController@storeHtml']);
    Route::get('/publicationfile/delete/{file_id}', 'PublicationsController@deleteFile');


    // ------------------------------------------------
    // Editing models
    // ------------------------------------------------

    // Documents
    Route::get('/document/{document_id}/destroy', 'DocumentController@destroy');
    Route::resource('document', 'DocumentController', ['except' => [ 'index', 'show', 'destroy' ]]);

    // Notices
    Route::get('/notice/{notice_id}/destroy', 'NoticeController@destroy');
    Route::resource('notice', 'NoticeController', ['except' => [ 'index', 'show', 'destroy' ]]);

    // Files
    Route::get('/file/{file_id}/destroy', 'FileController@destroy');
    Route::resource('file', 'FileController', ['except' => [ 'index', 'show', 'destroy' ]]);

    // Photos and Carousel photos
    Route::get('/carousel/update', 'ImageController@editCarousel');
    Route::post('/carousel/store', 'ImageController@postUpload');
    Route::get('/image/delete/{name}/{type}', 'ImageController@delete');
    Route::post('/textimage/store', 'ImageController@uploadTextImage');

    // Photoalbums
    Route::get('/album/create', 'AdminController@createAlbum');
    Route::post('/album/store', 'AdminController@storeAlbum');
    Route::get('/album/{name}/edit', 'AdminController@editAlbum');
    Route::get('/album/{id}/delete', 'AdminController@deleteAlbum');
    Route::post('/photo/store', 'ImageController@postUpload');

    // Articles
    Route::resource('article', 'ArticlesController', ['except' => ['destroy']]);
    Route::get('/article/{id}/destroy', 'ArticlesController@destroy');

    // Content of pages
    Route::get('/{page}/edit', 'AdminController@editPage');
    Route::post('/{page}/save', 'AdminController@save');
});

// Albums and Galleries manipulation
Route::get('/albums/{year}', 'PagesController@showAlbums');
Route::get('/gallery/{name}', 'PagesController@showGallery');

// Displaying publications (sudo code for the old ones when possible)
Route::group(['prefix' => '/zverejnovanie'], function() {
    Route::get('/', 'PagesController@displayPublicationsIndex');
    Route::get('/archiv/{rok}', 'PagesController@displayArchivedPublications');
    Route::get('/display/{year}/{type}', 'PagesController@displayPublications');
});

// New form for acitvities
Route::get('/temp/aktivity', 'ArticlesController@index');

// Matches URL to Content
Route::get('/', 'PagesController@matchTemplate' );
Route::get('/{template}', 'PagesController@matchTemplate');

resources/views/admin/album.blade.php
@extends("layouts.admin")

@section("content")

	<div class="page-header">
		<h2>Editácia albumu: {{ $album->name }} / <small>{{ $album->year }}</small></h2>
	</div>

	<div class="container">

		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3>Aktuálne obrázky v albume <small>{{ $album->name }}</small></h3>
					</div>
					<div class="panel-body">
						@if(count($images) != 0)
							<div class="row">

								@foreach($images as $image)
									<div class="col-md-2">
										<div class="thumbnail">
											<img src="{{ URL::asset('photos/albums/thumbs/'. $image->filename . '.jpg') }}">
											<div class="caption">
												<p>
													<a href="/image/delete/{{ $image->filename }}/photo" class="btn btn-danger delete-link confirm-deletion" role="button" data-subject="obrázok">Vymazať obrázok</a>
												</p>
											</div>
										</div>
									</div>
								@endforeach

							</div>
						@else
							Žiadne obrázky v tomto albume
						@endif
					</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">

					<div class="panel-heading">
						<h3>Nahrávanie nových obrázkov do tohto albumu</h3>
					</div>

					<div class="panel-body">
						<form action="/photo/store" class="dropzone" id="carousel-dropzone">
							{!! csrf_field() !!}
							<input type="hidden" name="photoalbum_id" value="{{ $album->id }}">
						</form>
					</div>

				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3>Vymazanie fotoalbumu</h3>
					</div>
					<div class="panel-body">
						<a href="/album/{{ $album->id }}/delete/" class="btn btn-danger confirm-deletion" data-subject="fotoalbum">Vymazať fotoalbum</a>
					</div>
				</div>
			</div>
		</div>
		
	</div>

@endsection

resources/views/admin/carousel.blade.php
@extends("layouts.admin")

@section("content")

	<div class="page-header">
		<h2>Editujete obrázky na uvítacej stránke </h2>
	</div>

	<div class="container">

		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3>Aktuálne obrázky na úvode</h3>
					</div>
					<div class="panel-body">

						@if(count($images) != 0)

							@foreach($images as $image)
								<div class="panel">
									<div class="panel-heading">
										<a href="/image/delete/{{ $image->name }}/carousel" class="btn btn-danger confirm-deletion delete-link" data-subject="obrázok">Vymazať obrázok</a>
									</div>
									<div class="panel-body">
										<img src="{{ URL::asset('photos/carousel_images/'. $image->name . '.jpg') }}" class="img_centered" width="400">
									</div>
								</div>
							@endforeach

						@else
							Žiadne obrázky na úvodnej stránke

						@endif

					</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3>Nahrávanie nových obrázkov</h3>
					</div>
					<div class="panel-body">
						<form action="/carousel/store" class="dropzone" id="carousel-dropzone">
							{!! csrf_field() !!}
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

@endsection

resources/views/admin/dashboard.blade.php
@extends("layouts.admin")

@section("content")

	<div class="page-header">
		<h1>Administrátorské sekcia</h1>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<ul class="nav nav-pills nav-stacked">
				  <li role="presentation" id="page"><a href="{{ url('/admin/page') }}">Stránky</a></li>
				  <li role="presentation" id="document"><a href="{{ url('/admin/document') }}">Dokumenty</a></li>
				  <li role="presentation" id="album"><a href="{{ url('/admin/album') }}">Fotoalbumy</a></li>
				  <li role="presentation" id="notice"><a href="{{ url('/admin/notice') }}">Oznamy</a></li>
				  <li role="presentation" id="carouselPictures"><a href="{{ url('/admin/carouselPictures') }}">Obrázky na úvode stránky</a></li>
				  <li role="presentation" id="file"><a href="{{ url('/admin/file') }}">Ostatné súbory</a></li>
				  <li role="presentation" id="news"><a href="{{ url('/admin/news') }}">Aktuality</a></li>
				</ul>
			</div>

			<div class="col-md-9" id="admin-content">
				<div class="panel panel-default panel_page dashboard_panel">

					<div class="panel-heading">
						<h3>Stránky</h3>
					</div>

					<div class="panel-body no-padding">
						<ul class="list-group my-list-group">
							
							@foreach($pages as $page)

								<a href="/{{ $page->name }}/edit">
									<li class="list-group-item">{{ $page->fullname }}</li>
								</a>

							@endforeach

						</ul>
					</div>
				</div>

				<div class="panel panel-default panel_document dashboard_panel">
					<div class="panel-heading">
						<h3>Dokumenty</h3>
					</div>

					<div class="panel-body no-padding">
						<ul class="list-group my-list-group">

							<li class="list-group-item">
								<a href="/document/create" class="btn btn-success">
									+ pridať nový dokument
								</a>
							</li>

							@if($documents)
								@foreach($documents as $document)

									<a href="/document/{{ $document->id }}/edit">
										<li class="list-group-item">{{ $document->name }} <small>{{ $document->page->fullname }}</small></li>
									</a>

								@endforeach
							@endif

						</ul>
					</div>
				</div>

				<div class="panel panel-default panel_album dashboard_panel">
					<div class="panel-heading">
						<h3>Fotoalbumy <small>a fotky</small></h3>
					</div>

					<div class="panel-body no-padding">
						<ul class="list-group my-list-group">

							<li class="list-group-item">
								<a href="/album/create" class="btn btn-success">
									+ vytvoriť nový album
								</a>
							</li>

							@foreach($albums as $album)

								<a href="/album/{{ $album->name }}/edit">
									<li class="list-group-item">{{ $album->name }} <small>{{$album->year  }}</small></li>
								</a>

							@endforeach
						</ul>
					</div>
				</div>

				<div class="panel panel-default panel_carouselPictures dashboard_panel">
					<div class="panel-heading">
						<h3>Obrázky na úvode stránky</h3>
					</div>

					<div class="panel-body no-padding">
						<ul class="list-group my-list-group">
							<li class="list-group-item">
								<a href="/carousel/update" class="btn btn-warning">
									Zmeniť obrázky na úvode stránky
								</a>
							</li>
						</ul>
					</div>
				</div>

				<div class="panel panel-default panel_notice dashboard_panel">
					<div class="panel-heading">
						<h3>Oznamy <small>na stránkach</small></h3>
					</div>
					<div class="panel-body no-padding">
						<ul class="list-group my-list-group">

							@if($notices)
								@foreach($notices as $notice)
									<a href="/notice/{{ $notice->id }}/edit">
										<li class="list-group-item">
											Oznam stránky: {{ $notice->page->fullname }}
										</li>
									</a>
								@endforeach
							@endif

							<li class="list-group-item">
								<a href="/notice/create" class="btn btn-success">
									+ pridať nový oznam
								</a>
							</li>
						</ul>
					</div>
				</div>

				<div class="panel panel-default panel_file dashboard_panel">
					<div class="panel-heading">
						<h3>Ostatné súbory <small>kliknite pre skopírovanie linku</small></h3>
					</div>

					<div class="panel-body no-padding">

						<ul class="list-group my-list-group">

							@if($files)
								@foreach($files as $file)
									<a href="#" class="copy-content" data-path="{{ getenv('BASE_URL') . $file->path }}">
										<li class="list-group-item">
										
											<div class="row">
												<div class="col-md-8">
													{{ $file->name }}
													<small><a href="{{ $file->path }}" target="_blank">prezrieť / stiahnuť súbor</a></small>
												</div>
												<div class="col-md-4">
													<a href="/file/{{ $file->id }}/destroy" class="pull-right confirm-deletion" data-subject="súbor">
														vymazať <i class="fa fa-times fa-lg"></i>
													</a>
												</div>
											</div>
										</li>
									</a>
								@endforeach
							@endif

							<span class="copy" style="display:none;visibility:hidden;"></span>

							<li class="list-group-item">
								<a href="/file/create" class="btn btn-success">
									+ pridať nový súbor
								</a>
							</li>
						</ul>

					</div>
				</div>

				<div class="panel panel-default panel_news dashboard_panel">
					<div class="panel-heading">
						<h3>Aktuality</h3>
					</div>
					<div class="panel-body no-padding">

						<ul class="list-group my-list-group">

							@if($articles)
								@foreach($articles as $article)
									<a href="#">
										<li class="list-group-item">
										
											<div class="row">
												<div class="col-md-8">
													<a href="{{ route('article.edit', $article->id) }}">{{ $article->title }}</a>
												</div>
												<div class="col-md-4">
													<a href="{{ url('/article/'.$article->id.'/destroy') }}" class="pull-right confirm-deletion" data-subject="aktualitu">
														vymazať <i class="fa fa-times fa-lg"></i>
													</a>
												</div>
											</div>
										</li>
									</a>
								@endforeach
							@endif

							<li class="list-group-item">
								<a href="/article/create" class="btn btn-success">
									+ pridať novú aktualitu
								</a>
							</li>
						</ul>
					</div>
				</div>

			</div>
		</div>
	</div>
@endsection

resources/views/admin/index.blade.php
@extends("layouts.admin")

@section("content")

	<h1>Prihlásiť sa</h1>

	<div class="container">
	    <div class="row">
	        <div class="col-md-8 col-md-offset-2">
	            <div class="panel panel-default">
	                <div class="panel-heading">Prihlásenie sa</div>
	                <div class="panel-body">
	                    <form class="form-horizontal" role="form" method="POST" action="/auth">

	                        {!! csrf_field() !!}

	                        <div class="form-group">
	                            <label class="col-md-4 control-label">E-mailová adresa</label>

	                            <div class="col-md-6">
	                                <input type="email" class="form-control" name="email">
	                            </div>
	                        </div>

	                        <div class="form-group">
	                            <label class="col-md-4 control-label">Heslo</label>

	                            <div class="col-md-6">
	                                <input type="password" class="form-control" name="password">
	                            </div>
	                        </div>

	                        <div class="form-group">
	                            <div class="col-md-6 col-md-offset-4">
	                                <button type="submit" class="btn btn-primary">
	                                    <i class="fa fa-btn fa-sign-in"></i> Prihlásiť sa
	                                </button>
	                            </div>
	                        </div>
	                    </form>
	                </div>
	            </div>
	        </div>
	    </div>
	</div>

@endsection

resources/views/admin/photos.blade.php
@extends("layouts.admin")

@section("content")

	<div class="page-header">
		<h2>Vytvorenie nového fotoalbumu</h2>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3>Fotoalbum</h3>
					</div>
					<div class="panel-body">
						<div class="form-group">

							<form method="post" action="/album/store">
								{!! csrf_field() !!}

								<div class="input-group">
									<span class="input-group-addon" id="basic-addon1">Názov albumu: </span>
									<input type="text" class="form-control" aria-describedby="basic-addon1" name="album_name">
								</div>

								<br />

								<div class="input-group">
									<span class="input-group-addon" id="basic-addon1">Školský rok: </span>
									<input type="text" placeholder="Vo formáte: 2015/2016" class="form-control" aria-describedby="basic-addon1" name="album_year">
								</div>

								<br />

								<button class="btn btn-success" type="submit">
									Vytvoriť nový album
								</button>

							</form>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

@endsection