app/Http/routes.php
<?php

// Authentication routes
Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/landingpage', 'PagesController@landingpage');

    // ------------------------------------------------
    // Auth routes
    // ------------------------------------------------

    Route::get('/auth', 'PagesController@showLogin');
    Route::post('/auth', 'AuthController@login');
    Route::get('/logout', ['as' => 'logout', 'uses' => 'AuthController@logout']);
    Route::get('/admin/{category}', ['as' => 'dashboard', 'uses' => 'AdminController@showDashboard']);
    Route::get('/admin', ['as' => 'dashboard', 'uses' => 'AdminController@showDashboard']);

    // ------------------------------------------------
    // Publications
    // ------------------------------------------------

    Route::get('/publication/{year}', 'PublicationsController@index');
    Route::get('/publicationsfiles', 'PublicationsController@fileManager');
    Route::resource('/publication', 'PublicationsController', ['except' => ['destroy']]);
    Route::get('/publication/{id}/destroy', 'PublicationsController@destroy');
    Route::get('/publication/create/{type}', 'PublicationsController@create');
    Route::post('/publication/filter', 'PublicationsController@filter');
    Route::post('/publication/storeFiles', 'PublicationsController@storeFile');
    Route::post('/publications/storeHtml', ['as' => 'publication.storeHtml', 'uses' => 'PublicationsController@storeHtml']);
    Route::get('/publicationfile/delete/{file_id}', 'PublicationsController@deleteFile');


    // ------------------------------------------------
    // Editing models
    // ------------------------------------------------

    // Documents
    Route::get('/document/{document_id}/destroy', 'DocumentController@destroy');
    Route::resource('document', 'DocumentController', ['except' => [ 'index', 'show', 'destroy' ]]);

    // Notices
    Route::get('/notice/{notice_id}/destroy', 'NoticeController@destroy');
    Route::resource('notice', 'NoticeController', ['except' => [ 'index', 'show', 'destroy' ]]);

    // Files
    Route::get('/file/{file_id}/destroy', 'FileController@destroy');
    Route::resource('file', 'FileController', ['except' => [ 'index', 'show', 'destroy' ]]);

    // Photos and Carousel photos
    Route::get('/carousel/update', 'ImageController@editCarousel');
    Route::post('/carousel/store', 'ImageController@postUpload');
    Route::get('/image/delete/{name}/{type}', 'ImageController@delete');
    Route::post('/textimage/store', 'ImageController@uploadTextImage');

    // Photoalbums
    Route::get('/album/create', 'AdminController@createAlbum');
    Route::post('/album/store', 'AdminController@storeAlbum');
    Route::get('/album/{name}/edit', 'AdminController@editAlbum');
    Route::get('/album/{id}/delete', 'AdminController@deleteAlbum');
    Route::post('/photo/store', 'ImageController@postUpload');

    // Articles
    Route::resource('article', 'ArticlesController', ['except' => ['destroy']]);
    Route::get('/article/{id}/destroy', 'ArticlesController@destroy');

    // Content of pages
    Route::get('/{page}/edit', 'AdminController@editPage');
    Route::post('/{page}/save', 'AdminController@save');
});

// Albums and Galleries manipulation
Route::get('/albums/{year}', 'PagesController@showAlbums');
Route::get('/gallery/{name}', 'PagesController@showGallery');

// Displaying publications (sudo code for the old ones when possible)
Route::group(['prefix' => '/zverejnovanie'], function() {
    Route::get('/', 'PagesController@displayPublicationsIndex');
    Route::get('/archiv/{rok}', 'PagesController@displayArchivedPublications');
    Route::get('/display/{year}/{type}', 'PagesController@displayPublications');
});

// New form for acitvities
Route::get('/temp/aktivity', 'ArticlesController@index');

// Matches URL to Content
Route::get('/', 'PagesController@matchTemplate' );
Route::get('/{template}', 'PagesController@matchTemplate');

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    /**
     * Table name for the model.
     * 
     * @var string
     */
    protected $table   = 'articles';
    
    /**
     * Include timestamps for this model.
     * 
     * @var boolean
     */
    public $timestamps = true;
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Models\Article;

use App\Repositories\ImageRepository;
use App\Repositories\FileRepository;

use Illuminate\Database\Eloquent\ModelNotFoundException;

class ArticlesController extends Controller
{
    /**
     * Constructor function for this controller.
     */
    public function __construct(ImageRepository $imageRepository, FileRepository $fileRepository) {
        $this->imageRepository = $imageRepository;
        $this->fileRepository  = $fileRepository;
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

    /**
     * Display a list with all the articles.
     * 
     * @return view
     */
    public function index() {
        $articles = Article::orderBy('created_at', 'desc')->paginate(20);
        return view('articles.index', compact("articles"));
    }

    /**
     * Dispaly the form for creating a new article.
     * 
     * @return view
     */
    public function create() {
        return view('articles.create');
    }

    /**
     * Stores the newly created article to the database.
     * 
     * @param  Request $request 
     */
    public function store(Request $request) {
        // create an image path
        $img_path = $this->imageRepository->uploadArticleHeadingImage($request->file('image'));

        // create a database record
        $article           = new Article;
        $article->title    = $request->title;
        $article->body     = $request->contents_for_saving;
        $article->img_path = $img_path;
        $article->save();

        // redirect back
        return redirect()->route('dashboard');
    }

    /**
     * Shows the form for editing an article.
     * 
     * @param  int $article_id
     * @return view            
     */
    public function edit($article_id) {
        $article = Article::where('id', $article_id)->firstOrFail();
        return view('articles.edit', compact("article"));
    }

    /**
     * Updates the article.
     * 
     * @param  int $article_id
     */
    public function update($article_id, Request $request) {
        $article = Article::where('id', $article_id)->firstOrFail();
        // create an image path, if there is any image
        if ($request->hasFile('image')) {
            $this->fileRepository->safeDeleteFile($article->img_path);
            $img_path          = $this->imageRepository->uploadArticleHeadingImage($request->file('image'));
            $article->img_path = $img_path;
        }

        $article->title = $request->title;
        $article->body  = $request->contents_for_saving;
        $article->save();

        return redirect()->route('dashboard');
    }

    /**
     * Deletes an article and image asscoaited with it as well.
     * 
     * @param  int $article_id
     * @return redirect
     */
    public function destroy($article_id) {
        try {
            $article = Article::where('id', $article_id)->firstOrFail();
            $this->fileRepository->safeDeleteFile($article->img_path);
            $article->delete();
        } catch (ModelNotFoundException $e) {
            return redirect()->back();
        }

        return redirect()->back();
    }
}

resources/views/articles/create.blade.php
@extends("layouts.admin")

@section('head')
	<script type="text/javascript" src="{{ URL::asset('ckeditor/ckeditor.js') }}"></script>
@endsection

@section("content")

	<div class="page-header">
		<h2>Vytvorenie novej aktuality</h2>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<form method="POST" action="{{ route('article.store') }}" id="page_form" enctype="multipart/form-data">

					{!! csrf_field() !!}

					<div class="panel panel-default">
						<div class="panel-heading">
							<h3>Nadpis</h3>
						</div>
						<div class="panel-body">
							<input type="text" name="title" placeholder="Nadpis vložte tu" class="form-control">
						</div>
					</div>

					<div class="panel panel-default">
						<div class="panel-heading">
							<h3>Text aktuality</h3>
						</div>
						<div class="panel-body">
							<textarea id="editable"></textarea>
						</div>
					</div>

					<div class="panel panel-default">
						<div class="panel-heading">
							<h3>Obrázok ku nadpisu</h3>
						</div>
						<div class="panel-body">
							<input type="file" name="image">
						</div>
					</div>

					<input type="hidden" value="" id="contents_for_saving" name="contents_for_saving" />

					<button id="save_article" type="submit" class="btn btn-primary">Uložiť aktualitu</button>
				</form>

			</div>
		</div>
	</div>

@endsection

resources/views/articles/edit.blade.php
@extends("layouts.admin")

@section('head')
    <script type="text/javascript" src="{{ URL::asset('ckeditor/ckeditor.js') }}"></script>
@endsection

@section("content")

    <div class="page-header">
        <h2>Editácia aktuality</h2>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <form method="POST" action="{{ route('article.update', $article->id) }}" id="page_form" enctype="multipart/form-data">
                <input name="_method" type="hidden" value="PUT">

                    {!! csrf_field() !!}

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3>Nadpis</h3>
                        </div>
                        <div class="panel-body">
                            <input
                                type="text"
                                name="title"
                                placeholder="Nadpis vložte tu"
                                class="form-control"
                                value="{{ $article->title }}"
                            >
                        </div>
                    </div>

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3>Text aktuality</h3>
                        </div>
                        <div class="panel-body">
                            <textarea id="editable">
                                @if($article->body)
                                    {{ $article->body }}
                                @endif
                            </textarea>
                        </div>
                    </div>

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3>Obrázok ku nadpisu</h3>
                        </div>
                        <div class="panel-body">
                            <input type="file" name="image">
                        </div>
                    </div>

                    <input type="hidden" value="" id="contents_for_saving" name="contents_for_saving" />

                    <button id="save_article" type="submit" class="btn btn-primary">Uložiť aktualitu</button>
                </form>

            </div>
        </div>
    </div>

@endsection

resources/views/articles/index.blade.php
@extends('layouts.page')

@section('content')

    <div class="divider"></div>

    <div class="wrapper">

        <div class="page fullpage">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h2 style="font-size:24px"><span style="font-size:30px">A</span>ktivity školy</h2>

                        <ul class="no-padding buffer-top-md">
                            @foreach($articles as $article)
                                <li>
                                    <div>
                                        <img src="{{ env('BASE_URL') . $article->img_path }}">
                                        <span style="color:#FF9900;font-weight:bold;vertical-align:bottom;font-size:16px;font-family:Tahoma;">
                                            {{ $article->title }}
                                        </span>                                    
                                    </div>
                                    <p class="width_100">
                                        {!! $article->body !!}
                                    </p>
                                </li>
                            @endforeach
                        </ul>

                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    {!! $articles->links() !!}
                </div>
            </div>
        </div>

    </div>

@endsection